services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VUE_APP_AKEY: "AIzaSyBNnGdquzgVmtshJ8Llo1eo3bF7vyIQPYM"
        VUE_APP_ADOMAIN: "shellblogs-863ee.firebaseapp.com"
        VUE_APP_PID: "shellblogs-863ee"
        VUE_APP_SBUCKET: "shellblogs-863ee.firebasestorage.app"
        VUE_APP_MSID: "795361965532"
        VUE_APP_AID: "1:795361965532:web:6e8076bbe5ced232ce4b19"
    ports:
      - '8080:80'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure